name: "helm-render-values"
version: "0.2.6"
ignoreFlags: false
description: |-
  Render value-file as a template and use it.
downloaders:
- command: "render-values"
  protocols:
    - "render"

hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
